### ISSUE TITLE
Need to add support for new Hue Bridge Whitelist format

### ISSUE THREAD

**Issue by ccicchitelli** [Q42/Q42.HueApi#61] opened 2016-04-08 07:49 UTC
We finally understand why some customers have been reporting issues in recent weeks with the Hue bridge, it seems Philips has rolled out some planned changes early, probably as part of testing. At this point, it seems all new Hue bridges may have the new firmware, so this library would need to update to match. 

http://www.developers.meethue.com/documentation/important-whitelist-changes

Thanks!!

**Comment by niels9001** [comment] 2016-04-08 07:59
Yep, so it's basically removing the possibility to add a 'custom' username.

**Comment by michielpost** [comment] 2016-04-08 08:03
Q42.HueApi has already been updated last year to support this new format.

See here: https://github.com/Q42/Q42.HueApi/blob/master/src/Q42.HueApi/LocalHueClient-Api.cs#L44

Maybe you are using an old version of the library? Or your users have an old version of the app?
Let me know if something is not working as expected.

**Comment by ccicchitelli** [comment] 2016-04-08 16:39
The line you point to is about the device type format, but I'm referring to the replacement of the AppKey that is use (our app) supplied with the username that is supplied by the Hue bridge.

**Comment by michielpost** [comment] 2016-04-08 17:36
Yes, the result of the API call is the username which is read from the response and returned. See this line:
https://github.com/Q42/Q42.HueApi/blob/master/src/Q42.HueApi/LocalHueClient-Api.cs#L74

**Comment by ccicchitelli** [comment] 2016-04-08 17:39
Perhaps I'm not interpreting the report from the customers correctly. Unfortunately, we're unable to replicate this in house, but enough people are complaining now that we know there is definitely a problem somewhere, and the problem is recent. Here's what I based this thread on, but he's just one of several with the same issue:

http://www.castleos.com/forum/topic860-hard-time-geting-hue-hub-added.aspx

**Comment by michielpost** [comment] 2016-04-08 20:03
Looking at the json this user posted on the CastleOS forum he has API version: "apiversion": "1.12.0".

Philips does not have any info about it. Their latest update is about 1.11: http://www.developers.meethue.com/documentation/changelog

So we can only guess about the whitelist change, but not sure what else is different.

What version does the bridge have you are testing with?

**Comment by niels9001** [comment] 2016-04-08 20:48
It's probably API version 1.13: this is bringing the whitelist change.

All older apps that use a custom username to register the app will no longer work (users that already connected to the Bridge can continue to use it of course).

Philips has been doing some a/b / beta testing in the last couple of weeks, and I think they want to release this update to all Bridges in 1 or 2 weeks (I received an e-mail that my app was not compliant, that's why I know).

I have version 1.13 installed on my Bridge (because I am in the BETA program).

**Comment by ccicchitelli** [comment] 2016-04-08 20:58
Our test unit is 1.11. So this does seem to be an issue with 1.12 and 1.13. What can we do to help you test it?

**Comment by michielpost** [comment] 2016-04-09 10:49
@niels9001 are you able to test against the 1.13 api version and check if everything is working as expected or if there are breaking changes?

**Comment by ccicchitelli** [comment] 2016-04-09 20:46
We got pushed 1.12... lights still work with previously authenticated apps, but I'm going to try to auth with a brand new install and see what happens...

**Comment by niels9001** [comment] 2016-04-10 15:37
I was using version 1.9.x of Q42.HueApi in my WP8.1 app before, and that didn’t work. 

Latest version works great! It requires some code changes of course (RegisterBridgeAsync should now be used), but I can confirm that it works on Windows Phone 8.1 and Windows 10.

Niels

**Comment by ccicchitelli** [comment] 2016-04-10 18:48
I'm confused, are you saying it now works with 1.13?

**Comment by niels9001** [comment] 2016-04-10 19:54
Yep, latest NuGet pacages + Hue API version 1.13 work great together:


RegisterBridge br = new RegisterBridge();

string UserName = await br.RegisterAsync("AppName", AnalyticsInfo.VersionInfo.DeviceFamily, IPAddress);

**Comment by ccicchitelli** [comment] 2016-04-10 20:01
Is RegisterBridge your own custom class, or part of the Q42 API?

We initialize differently:

ILocalHueClient client = new LocalHueClient(ip);
string appKey = await client.RegisterAsync("CastleOS", "CastleOSAppKey");

**Comment by niels9001** [comment] 2016-04-18 13:31
I think it is somewhere in the API, not 100% sure though. This is the code:

`public sealed class RegisterBridge
    {
        public async Task<string> RegisterAsync(string applicationName, string deviceName, string _ip)
        {
            if (applicationName == null)
                throw new ArgumentNullException("applicationName");
            if (applicationName.Trim() == String.Empty)
                throw new ArgumentException("applicationName must not be empty", "applicationName");
            if (applicationName.Length > 20)
                throw new ArgumentException("applicationName max is 20 characters.", "applicationName");
            if (applicationName.Contains(" "))
                throw new ArgumentException("Cannot contain spaces.", "applicationName");

            if (deviceName == null)
                throw new ArgumentNullException("deviceName");
            if (deviceName.Length < 0 || deviceName.Trim() == String.Empty)
                throw new ArgumentException("deviceName must be at least 0 characters.", "deviceName");
            if (deviceName.Length > 19)
                throw new ArgumentException("deviceName max is 19 characters.", "deviceName");
            if (deviceName.Contains(" "))
                throw new ArgumentException("Cannot contain spaces.", "deviceName");

            string fullName = string.Format("{0}#{1}", applicationName, deviceName);

            JObject obj = new JObject();
            obj["devicetype"] = fullName;

            HttpClient client = HueClient.GetHttpClient();
            var response = await client.PostAsync(new Uri(string.Format("http://{0}/api", _ip)), new StringContent(obj.ToString())).ConfigureAwait(false);
            var stringResponse = await response.Content.ReadAsStringAsync().ConfigureAwait(false);

            JObject result;
            try
            {
                JArray jresponse = JArray.Parse(stringResponse);
                result = (JObject)jresponse.First;
            }
            catch
            {
                //Not an expected response. Return response as exception
                throw new Exception(stringResponse);
            }

            JToken error;
            if (result.TryGetValue("error", out error))
            {
                if (error["type"].Value<int>() == 101) // link button not pressed
                    throw new Exception("Link button not pressed");
                else
                    throw new Exception(error["description"].Value<string>());
            }

            string key = result["success"]["username"].Value<string>();

            return key;
        }
    }`

**Comment by michielpost** [comment] 2016-05-03 10:48
Confirmed by @niels9001 "latest NuGet pacages + Hue API version 1.13 work great together".
Closing this issue.

**Closed by michielpost** 2016-05-03 10:48 UTC
